In [1]:
import numpy as np

In [2]:
a = np.zeros((2,5))

In [3]:
print(a)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [4]:
d = np.random.random((2,6))

In [5]:
print(d)

[[0.15568632 0.82092561 0.4149415  0.8167392  0.4449316  0.58337022]
 [0.29459732 0.75699624 0.06515255 0.40416428 0.10666381 0.7975653 ]]


In [6]:
b = np.ones((2,3))

In [7]:
print(b)

[[1. 1. 1.]
 [1. 1. 1.]]


In [9]:
c = np.arange(1,6)

In [10]:
c

array([1, 2, 3, 4, 5])

In [11]:
print(np.max(d))

0.8209256092547391


In [12]:
print(np.min(d))

0.06515254747112287
